
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package browser.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFT = 29;
  public static final int HEXADECIMAL = 71;
  public static final int LINE_HOR_AB = 56;
  public static final int ITALICA_CE = 38;
  public static final int N_TILDE_MEN = 9;
  public static final int TYPE = 52;
  public static final int FONT_CE = 44;
  public static final int O_TILDE = 6;
  public static final int I_TILDE = 5;
  public static final int BGCOLOR = 23;
  public static final int RIGHT = 30;
  public static final int CIRCLE = 67;
  public static final int MAYOR = 11;
  public static final int NAME = 63;
  public static final int SQUARE = 68;
  public static final int NEGRILLA_AB = 33;
  public static final int BODY_AB = 18;
  public static final int SUBINDICE_CE = 42;
  public static final int LIST_ORD_CE = 50;
  public static final int PARRAFO_CE = 21;
  public static final int NOBR_AB = 54;
  public static final int ANCHO_PANTALLA = 75;
  public static final int SIGNO_IGUAL = 2;
  public static final int PARAMETRO = 77;
  public static final int HEAD_CE = 15;
  public static final int CENTER = 31;
  public static final int ENLACE_CE = 62;
  public static final int TEXT = 24;
  public static final int LIST_DES_CE = 48;
  public static final int CENTRADO_CE = 27;
  public static final int MIN = 73;
  public static final int CIERRE = 65;
  public static final int SALTO_LINEA = 22;
  public static final int SUBRAYADO_CE = 36;
  public static final int WIDTH = 58;
  public static final int ITALICA_AB = 37;
  public static final int FONT_AB = 43;
  public static final int A_TILDE = 3;
  public static final int ALIGN = 28;
  public static final int TACHADO_CE = 40;
  public static final int LIST_ORD_AB = 49;
  public static final int SUBINDICE_AB = 41;
  public static final int PARRAFO_AB = 20;
  public static final int FACE = 46;
  public static final int TITLE_CE = 17;
  public static final int MAY = 72;
  public static final int HTML_CE = 13;
  public static final int MENOR = 10;
  public static final int HEAD_AB = 14;
  public static final int SANGRIA_CE = 60;
  public static final int TEXTO_PLANO = 76;
  public static final int ENTERO_UNO = 70;
  public static final int N_TILDE_MAY = 8;
  public static final int LINK = 25;
  public static final int EOF = 0;
  public static final int ENLACE_AB = 61;
  public static final int LIST_DES_AB = 47;
  public static final int CENTRADO_AB = 26;
  public static final int DISC = 69;
  public static final int ITEM = 51;
  public static final int LINE_HOR_CE = 57;
  public static final int SUBRAYADO_AB = 35;
  public static final int TAMANO = 74;
  public static final int HREF = 64;
  public static final int error = 1;
  public static final int START = 53;
  public static final int NEGRILLA_CE = 34;
  public static final int BODY_CE = 19;
  public static final int JUSTIFIED = 32;
  public static final int E_TILDE = 4;
  public static final int ENLACE = 66;
  public static final int TACHADO_AB = 39;
  public static final int NOBR_CE = 55;
  public static final int TITLE_AB = 16;
  public static final int HTML_AB = 12;
  public static final int SIZE = 45;
  public static final int U_TILDE = 7;
  public static final int SANGRIA_AB = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SIGNO_IGUAL",
  "A_TILDE",
  "E_TILDE",
  "I_TILDE",
  "O_TILDE",
  "U_TILDE",
  "N_TILDE_MAY",
  "N_TILDE_MEN",
  "MENOR",
  "MAYOR",
  "HTML_AB",
  "HTML_CE",
  "HEAD_AB",
  "HEAD_CE",
  "TITLE_AB",
  "TITLE_CE",
  "BODY_AB",
  "BODY_CE",
  "PARRAFO_AB",
  "PARRAFO_CE",
  "SALTO_LINEA",
  "BGCOLOR",
  "TEXT",
  "LINK",
  "CENTRADO_AB",
  "CENTRADO_CE",
  "ALIGN",
  "LEFT",
  "RIGHT",
  "CENTER",
  "JUSTIFIED",
  "NEGRILLA_AB",
  "NEGRILLA_CE",
  "SUBRAYADO_AB",
  "SUBRAYADO_CE",
  "ITALICA_AB",
  "ITALICA_CE",
  "TACHADO_AB",
  "TACHADO_CE",
  "SUBINDICE_AB",
  "SUBINDICE_CE",
  "FONT_AB",
  "FONT_CE",
  "SIZE",
  "FACE",
  "LIST_DES_AB",
  "LIST_DES_CE",
  "LIST_ORD_AB",
  "LIST_ORD_CE",
  "ITEM",
  "TYPE",
  "START",
  "NOBR_AB",
  "NOBR_CE",
  "LINE_HOR_AB",
  "LINE_HOR_CE",
  "WIDTH",
  "SANGRIA_AB",
  "SANGRIA_CE",
  "ENLACE_AB",
  "ENLACE_CE",
  "NAME",
  "HREF",
  "CIERRE",
  "ENLACE",
  "CIRCLE",
  "SQUARE",
  "DISC",
  "ENTERO_UNO",
  "HEXADECIMAL",
  "MAY",
  "MIN",
  "TAMANO",
  "ANCHO_PANTALLA",
  "TEXTO_PLANO",
  "PARAMETRO"
  };
}

