
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package browser.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int COR_CE = 29;
  public static final int NUMERO = 37;
  public static final int DIFERENTE_QUE = 15;
  public static final int INTEGER = 2;
  public static final int DOS_PUNTOS = 31;
  public static final int FOR = 23;
  public static final int PAR_AB = 26;
  public static final int AND = 17;
  public static final int OR = 18;
  public static final int BEGIN = 35;
  public static final int IF = 19;
  public static final int PUNTO_COMA = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int MENOS = 8;
  public static final int PAR_CE = 27;
  public static final int MAYOR_QUE = 11;
  public static final int ASIGNACION = 30;
  public static final int COR_AB = 28;
  public static final int ELSE = 21;
  public static final int VARIABLE = 38;
  public static final int TO = 24;
  public static final int WHILE = 22;
  public static final int IGUAL_QUE = 16;
  public static final int MAYOR_IGUAL = 13;
  public static final int THEN = 20;
  public static final int END = 34;
  public static final int STRING = 4;
  public static final int MENOR_QUE = 12;
  public static final int TEXTO = 39;
  public static final int MENOR_IGUAL = 14;
  public static final int FALSE = 6;
  public static final int DIVISION = 10;
  public static final int VAR = 36;
  public static final int PRINT = 25;
  public static final int MULTIPLICACION = 9;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "STRING",
  "TRUE",
  "FALSE",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "DIFERENTE_QUE",
  "IGUAL_QUE",
  "AND",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "TO",
  "PRINT",
  "PAR_AB",
  "PAR_CE",
  "COR_AB",
  "COR_CE",
  "ASIGNACION",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "COMA",
  "END",
  "BEGIN",
  "VAR",
  "NUMERO",
  "VARIABLE",
  "TEXTO"
  };
}

